### ISSUE TITLE
workspace file chooser bombs on symlink with no destination

### ISSUE THREAD

**Issue by harryhoch** [bd2kccd/ccd-web#1]
The workspace file browser blew up on me.

I think the problem had to do with the reading of a file that was a dangling reference sym link - ie, the link existed, but the target file did not.

Probably best to revise the iteration code to skip over anything that comes up in the directory list of files but then has a NoSuchFile problem.

2015-07-06 13:15:13.137  INFO 14599 --- [           main] edu.pitt.dbmi.ccd.web.CCDWebApplication  : Started CCDWebApplication in 13.103 seconds (JVM running for 13.749)
Hibernate: select useraccoun0_."id" as id1_2_, useraccoun0_."active" as active2_2_, useraccoun0_."created_date" as created_3_2_, useraccoun0_."last_login_date" as last_log4_2_, useraccoun0_."password" as password5_2_, useraccoun0_.person_id as person_i7_2_, useraccoun0_."username" as username6_2_ from "user_account" useraccoun0_ where useraccoun0_."username"=?
java.nio.file.NoSuchFileException: /Users/harry/Documents/research/projects/bart-phoenix
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
    at java.nio.file.Files.readAttributes(Files.java:1737)
    at edu.pitt.dbmi.ccd.web.util.FileUtility.getDirListing(FileUtility.java:121)
    at edu.pitt.dbmi.ccd.web.ctrl.UserAccountController.browsingServerSideDirectory(UserAccountController.java:225)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)

**Comment by kvb2univpitt** [comment]
This issue was for the desktop version.  It is no longer applicable.
