### ISSUE TITLE
Can't get sign up email 

### ISSUE THREAD

**Issue by yuanzhou** [bd2kccd/ccd-web#4]
I installed CCD-Web 1.2.0 and specified the gmail username and password. But after I went through the sign up new account process, I got this error:

```
[2016-03-16 14:17:56.707] boot - 30419  INFO [main] --- CcdWebApplication: Started CcdWebApplication in 14.536 seconds (JVM running for 14.927)
Exception in thread "Thread-16" org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: failed to connect, no password specified?
    at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:409)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:362)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:350)
    at edu.pitt.dbmi.ccd.mail.AbstractBasicMail.send(AbstractBasicMail.java:40)
    at edu.pitt.dbmi.ccd.mail.service.SimpleUserMailService.sendRegistrationActivation(SimpleUserMailService.java:60)
    at edu.pitt.dbmi.ccd.web.service.mail.MailService.sendRegistrationActivation(MailService.java:58)
    at edu.pitt.dbmi.ccd.web.service.UserService.lambda$registerNewUser$24(UserService.java:123)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.AuthenticationFailedException: failed to connect, no password specified?
    at javax.mail.Service.connect(Service.java:398)
    at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:486)
    at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:406)
    ... 8 more
```

I had this work couple months ago and since the `ccd-mail` master branch hasn't been updated since 4 months, I suspect something is not right in CCD-Web.

**Comment by yuanzhou** [comment]
Restarted the server and it worked this time.
